version: "3.8"

services:
  backend:
    build:
      context: ./backend # Path to the directory containing the backend Dockerfile
    ports:
      - "8000:8000"
    # depends_on:
    #   - database
    # environment:
    #   SQLALCHEMY_DATABASE_URL: "sqlite:///./test.db" # Adjust this based on your database configuration

  frontend:
    build:
      context: ./frontend/parameter-visualization # Path to the directory containing the frontend Dockerfile
    ports:
      - "3000:3000"
